# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    key                  = "./terraform1.tfstate"
    resource_group_name  = "Ajinkya-RG1"
    storage_account_name = "store9291"
    container_name       = "tfstate01"
  }
}
